const fs = require('fs');
const path = require('path');

const C_FILES_REGEX = /.+(\.cpp|\.c|\.inc|\.h)$/;

const z64sceneMap = {
  'SCENE_YDAN': 'SCENE_DEKU_TREE',
  'SCENE_DDAN': 'SCENE_DODONGOS_CAVERN',
  'SCENE_BDAN': 'SCENE_JABU_JABU',
  'SCENE_BMORI1': 'SCENE_FOREST_TEMPLE',
  'SCENE_HIDAN': 'SCENE_FIRE_TEMPLE',
  'SCENE_MIZUSIN': 'SCENE_WATER_TEMPLE',
  'SCENE_JYASINZOU': 'SCENE_SPIRIT_TEMPLE',
  'SCENE_HAKADAN': 'SCENE_SHADOW_TEMPLE',
  'SCENE_HAKADANCH': 'SCENE_BOTTOM_OF_THE_WELL',
  'SCENE_ICE_DOUKUTO': 'SCENE_ICE_CAVERN',
  'SCENE_GANON': 'SCENE_GANONS_TOWER',
  'SCENE_MEN': 'SCENE_GERUDO_TRAINING_GROUND',
  'SCENE_GERUDOWAY': 'SCENE_THIEVES_HIDEOUT',
  'SCENE_GANONTIKA': 'SCENE_INSIDE_GANONS_CASTLE',
  'SCENE_GANON_SONOGO': 'SCENE_GANONS_TOWER_COLLAPSE_INTERIOR',
  'SCENE_GANONTIKA_SONOGO': 'SCENE_INSIDE_GANONS_CASTLE_COLLAPSE',
  'SCENE_TAKARAYA': 'SCENE_TREASURE_BOX_SHOP',
  'SCENE_YDAN_BOSS': 'SCENE_DEKU_TREE_BOSS',
  'SCENE_DDAN_BOSS': 'SCENE_DODONGOS_CAVERN_BOSS',
  'SCENE_BDAN_BOSS': 'SCENE_JABU_JABU_BOSS',
  'SCENE_MORIBOSSROOM': 'SCENE_FOREST_TEMPLE_BOSS',
  'SCENE_FIRE_BS': 'SCENE_FIRE_TEMPLE_BOSS',
  'SCENE_MIZUSIN_BS': 'SCENE_WATER_TEMPLE_BOSS',
  'SCENE_JYASINBOSS': 'SCENE_SPIRIT_TEMPLE_BOSS',
  'SCENE_HAKADAN_BS': 'SCENE_SHADOW_TEMPLE_BOSS',
  'SCENE_GANON_BOSS': 'SCENE_GANONDORF_BOSS',
  'SCENE_GANON_FINAL': 'SCENE_GANONS_TOWER_COLLAPSE_EXTERIOR',
  'SCENE_ENTRA': 'SCENE_MARKET_ENTRANCE_DAY',
  'SCENE_ENTRA_N': 'SCENE_MARKET_ENTRANCE_NIGHT',
  'SCENE_ENRUI': 'SCENE_MARKET_ENTRANCE_RUINS',
  'SCENE_MARKET_ALLEY': 'SCENE_BACK_ALLEY_DAY',
  'SCENE_MARKET_ALLEY_N': 'SCENE_BACK_ALLEY_NIGHT',
  'SCENE_MARKET_DAY': 'SCENE_MARKET_DAY',
  'SCENE_MARKET_NIGHT': 'SCENE_MARKET_NIGHT',
  'SCENE_MARKET_RUINS': 'SCENE_MARKET_RUINS',
  'SCENE_SHRINE': 'SCENE_TEMPLE_OF_TIME_EXTERIOR_DAY',
  'SCENE_SHRINE_N': 'SCENE_TEMPLE_OF_TIME_EXTERIOR_NIGHT',
  'SCENE_SHRINE_R': 'SCENE_TEMPLE_OF_TIME_EXTERIOR_RUINS',
  'SCENE_KOKIRI_HOME': 'SCENE_KNOW_IT_ALL_BROS_HOUSE',
  'SCENE_KOKIRI_HOME3': 'SCENE_TWINS_HOUSE',
  'SCENE_KOKIRI_HOME4': 'SCENE_MIDOS_HOUSE',
  'SCENE_KOKIRI_HOME5': 'SCENE_SARIAS_HOUSE',
  'SCENE_KAKARIKO': 'SCENE_KAKARIKO_CENTER_GUEST_HOUSE',
  'SCENE_KAKARIKO3': 'SCENE_BACK_ALLEY_HOUSE',
  'SCENE_SHOP1': 'SCENE_BAZAAR',
  'SCENE_KOKIRI_SHOP': 'SCENE_KOKIRI_SHOP',
  'SCENE_GOLON': 'SCENE_GORON_SHOP',
  'SCENE_ZOORA': 'SCENE_ZORA_SHOP',
  'SCENE_DRAG': 'SCENE_POTION_SHOP_KAKARIKO',
  'SCENE_ALLEY_SHOP': 'SCENE_POTION_SHOP_MARKET',
  'SCENE_NIGHT_SHOP': 'SCENE_BOMBCHU_SHOP',
  'SCENE_FACE_SHOP': 'SCENE_HAPPY_MASK_SHOP',
  'SCENE_LINK_HOME': 'SCENE_LINKS_HOUSE',
  'SCENE_IMPA': 'SCENE_DOG_LADY_HOUSE',
  'SCENE_MALON_STABLE': 'SCENE_STABLE',
  'SCENE_LABO': 'SCENE_IMPAS_HOUSE',
  'SCENE_HYLIA_LABO': 'SCENE_LAKESIDE_LABORATORY',
  'SCENE_TENT': 'SCENE_CARPENTERS_TENT',
  'SCENE_HUT': 'SCENE_GRAVEKEEPERS_HUT',
  'SCENE_DAIYOUSEI_IZUMI': 'SCENE_GREAT_FAIRYS_FOUNTAIN_MAGIC',
  'SCENE_YOUSEI_IZUMI_TATE': 'SCENE_FAIRYS_FOUNTAIN',
  'SCENE_YOUSEI_IZUMI_YOKO': 'SCENE_GREAT_FAIRYS_FOUNTAIN_SPELLS',
  'SCENE_KAKUSIANA': 'SCENE_GROTTOS',
  'SCENE_HAKAANA': 'SCENE_REDEAD_GRAVE',
  'SCENE_HAKAANA2': 'SCENE_GRAVE_WITH_FAIRYS_FOUNTAIN',
  'SCENE_HAKAANA_OUKE': 'SCENE_ROYAL_FAMILYS_TOMB',
  'SCENE_SYATEKIJYOU': 'SCENE_SHOOTING_GALLERY',
  'SCENE_TOKINOMA': 'SCENE_TEMPLE_OF_TIME',
  'SCENE_KENJYANOMA': 'SCENE_CHAMBER_OF_THE_SAGES',
  'SCENE_HAIRAL_NIWA': 'SCENE_CASTLE_COURTYARD_GUARDS_DAY',
  'SCENE_HAIRAL_NIWA_N': 'SCENE_CASTLE_COURTYARD_GUARDS_NIGHT',
  'SCENE_HIRAL_DEMO': 'SCENE_CUTSCENE_MAP',
  'SCENE_HAKASITARELAY': 'SCENE_WINDMILL_AND_DAMPES_GRAVE',
  'SCENE_TURIBORI': 'SCENE_FISHING_POND',
  'SCENE_NAKANIWA': 'SCENE_CASTLE_COURTYARD_ZELDA',
  'SCENE_BOWLING': 'SCENE_BOMBCHU_BOWLING_ALLEY',
  'SCENE_SOUKO': 'SCENE_LON_LON_BUILDINGS',
  'SCENE_MIHARIGOYA': 'SCENE_MARKET_GUARD_HOUSE',
  'SCENE_MAHOUYA': 'SCENE_POTION_SHOP_GRANNY',
  'SCENE_GANON_DEMO': 'SCENE_GANON_BOSS',
  'SCENE_KINSUTA': 'SCENE_HOUSE_OF_SKULLTULA',
  'SCENE_SPOT00': 'SCENE_HYRULE_FIELD',
  'SCENE_SPOT01': 'SCENE_KAKARIKO_VILLAGE',
  'SCENE_SPOT02': 'SCENE_GRAVEYARD',
  'SCENE_SPOT03': 'SCENE_ZORAS_RIVER',
  'SCENE_SPOT04': 'SCENE_KOKIRI_FOREST',
  'SCENE_SPOT05': 'SCENE_SACRED_FOREST_MEADOW',
  'SCENE_SPOT06': 'SCENE_LAKE_HYLIA',
  'SCENE_SPOT07': 'SCENE_ZORAS_DOMAIN',
  'SCENE_SPOT08': 'SCENE_ZORAS_FOUNTAIN',
  'SCENE_SPOT09': 'SCENE_GERUDO_VALLEY',
  'SCENE_SPOT10': 'SCENE_LOST_WOODS',
  'SCENE_SPOT11': 'SCENE_DESERT_COLOSSUS',
  'SCENE_SPOT12': 'SCENE_GERUDOS_FORTRESS',
  'SCENE_SPOT13': 'SCENE_HAUNTED_WASTELAND',
  'SCENE_SPOT15': 'SCENE_HYRULE_CASTLE',
  'SCENE_SPOT16': 'SCENE_DEATH_MOUNTAIN_TRAIL',
  'SCENE_SPOT17': 'SCENE_DEATH_MOUNTAIN_CRATER',
  'SCENE_SPOT18': 'SCENE_GORON_CITY',
  'SCENE_SPOT20': 'SCENE_LON_LON_RANCH',
  'SCENE_GANON_TOU': 'SCENE_OUTSIDE_GANONS_CASTLE',
  'SCENE_TEST01': 'SCENE_TEST01',
  'SCENE_BESITU': 'SCENE_BESITU',
  'SCENE_DEPTH_TEST': 'SCENE_DEPTH_TEST',
  'SCENE_SYOTES': 'SCENE_SYOTES',
  'SCENE_SYOTES2': 'SCENE_SYOTES2',
  'SCENE_SUTARU': 'SCENE_SUTARU',
  'SCENE_HAIRAL_NIWA2': 'SCENE_HAIRAL_NIWA2',
  'SCENE_SASATEST': 'SCENE_SASATEST',
  'SCENE_TESTROOM': 'SCENE_TESTROOM',
};

const variablesMap = {
  '__osPifInternalBuff': '__osContPifRam',
  '__osContLastPoll': '__osContLastCmd',
  'osAppNmiBuffer': 'osAppNMIBuffer',

  'D_80013960': 'gViConfigModeType',
  'D_8011FB34': 'gLightConfigAfterUnderwater',
  'D_8011FB38': 'gInterruptSongOfStorms',
  'D_80125DE8': 'gPlayerLeftHandBgsDLs',
  'D_80125E08': 'gPlayerLeftHandOpenDLs',
  'D_80125E18': 'gPlayerLeftHandClosedDLs',
  'D_80125EF8': 'gPlayerLeftHandBoomerangDLs',
  'D_8012D1F0': 'gDebugCutsceneScript',
  'D_808535F4': 'sConveyorSpeedIndex',
  'D_808535FC': 'sConveyorYaw',
  'D_801333D4': 'gSfxDefaultPos',
  'D_801333E0': 'gSfxDefaultFreqAndVolScale',
  'D_801333E8': 'gSfxDefaultReverb',
  'D_8014A6C4': 'gAudioHeapInitSizes',
  'D_8016E750': 'gActiveSeqs',
  'D_80009460': 'gDmaMgrVerbose',
  'D_801614B0': 'gVisMonoColor',

  'gViConfigUseDefault': 'gViConfigBlack',
  'gPiMgrCmdQ': 'gPiMgrCmdQueue',
  'gDbgCamEnabled': 'gDebugCamEnabled',
  'gTimeIncrement': 'gTimeSpeed',
  'gPifMempakBuf': '__osPfsPifRam',
  'gNoteFrequencies': 'gPitchFrequencies',
  'gHeadsetPanQuantization': 'gHaasEffectDelaySizes',
  'gSoundParams': 'gSfxParams',
  'gSoundBanks': 'gSfxBanks',
  'gAudioContext': 'gAudioCtx',
  'gLensFlareScreenFillAlpha': 'gLensFlareGlareStrength',
  'gTrnsnUnkState': 'gTransitionTileState',
  'gAudioContextInitalized': 'gAudioContextInitialized',
  'gScarecrowCustomSongPtr': 'gScarecrowLongSongPtr',
  'gOcarinaSongNotes': 'gOcarinaSongButtons',
  'gIsLargeSoundBank': 'gIsLargeSfxBank',

  'sLowPassFilterData': 'gLowPassFilterData',
  'sHighPassFilterData': 'gHighPassFilterData',

  'feetFloorFlags': 'feetFloorFlag',
  'stickRelX': 'stickAdjX',
  'stickRelY': 'stickAdjY',
  'pageSwitchTimer': 'pageSwitchInputTimer',
  'sceneNum': 'sceneId',
  'savedSceneNum': 'savedSceneId',
  'sceneSetupIndex': 'sceneLayer',
  'setupPathList': 'pathList',
  'unk_11DE9': 'haltAllActors',
  'sceneLoadFlag': 'transitionTrigger',
  'swordState': 'meleeWeaponState',
  'fadeTransition': 'transitionType',
};

const functionsMap = {
  'Audio_PlaySoundGeneral': 'Audio_PlaySfxGeneral',
  'Audio_PlayActorSound2': 'Actor_PlaySfx',
  'Audio_OcaGetDisplayingStaff': 'AudioOcarina_GetPlaybackStaff',
  'Audio_OcaSetInstrument': 'AudioOcarina_SetInstrument',
  'Audio_OcaSetSongPlayback': 'Audio_OcaSetSongPlayback',
  'Message_StartOcarina': 'Message_StartOcarinaImpl',
  'Audio_GetSfx': 'Audio_GetSoundEffect',
  'Audio_InstrumentGetSound': 'Audio_GetInstrumentTunedSample',
  'Audio_OcaSetSongPlayback': 'AudioOcarina_SetPlaybackSong',
  'Audio_OcaSetRecordingState': 'AudioOcarina_SetRecordingState',
  'Audio_OcaGetRecordingStaff': 'AudioOcarina_GetRecordingStaff',
  'Audio_OcaGetPlayingStaff': 'AudioOcarina_GetPlayingStaff',
  'Audio_OcaMemoryGameStart': 'AudioOcarina_MemoryGameInit',
  'Audio_OcaMemoryGameGenNote': 'AudioOcarina_MemoryGameNextNote',
  'Audio_SetSoundProperties': 'Audio_SetSfxProperties',
  'Audio_PlaySoundRandom': 'Audio_PlaySfxRandom',
  'Audio_PlaySoundRiver': 'Audio_PlaySfxRiver',
  'Audio_PlaySoundWaterfall': 'Audio_PlaySfxWaterfall',
  'Audio_PlaySoundIncreasinglyTransposed': 'Audio_PlaySfxIncreasinglyTransposed',
  'Audio_PlaySoundTransposed': 'Audio_PlaySfxTransposed',
  'Audio_PlaySoundIfNotInCutscene': 'Audio_PlaySfxIfNotInCutscene',
  'Audio_SetSoundBanksMute': 'Audio_SetSfxBanksMute',
  'Audio_ProcessSoundRequest': 'Audio_ProcessSfxRequest',
  'Audio_ChooseActiveSounds': 'Audio_ChooseActiveSfx',
  'Audio_PlayActiveSounds': 'Audio_PlayActiveSfx',
  'Audio_ProcessSoundRequests': 'Audio_ProcessSfxRequests',
  'Audio_ResetSounds': 'Audio_ResetSfx',

  'BgCheck_EntityRaycastFloor1': 'BgCheck_EntityRaycastDown1',
  'BgCheck_EntityRaycastFloor2': 'BgCheck_EntityRaycastDown2',
  'BgCheck_EntityRaycastDown3': 'BgCheck_EntityRaycastDown3',
  'BgCheck_EntityRaycastDown4': 'BgCheck_EntityRaycastDown4',
  'BgCheck_EntityRaycastDown5': 'BgCheck_EntityRaycastDown5',
  'BgCheck_EntityRaycastFloor6': 'BgCheck_EntityRaycastDown6',
  'BgCheck_EntityRaycastFloor7': 'BgCheck_EntityRaycastDown7',
  'BgCheck_AnyRaycastFloor1': 'BgCheck_AnyRaycastDown1',
  'BgCheck_AnyRaycastFloor2': 'BgCheck_AnyRaycastDown2',
  'BgCheck_CameraRaycastFloor2': 'BgCheck_CameraRaycastDown2',
  'BgCheck_EntityRaycastFloor8': 'BgCheck_EntityRaycastDownWalls',
  'BgCheck_EntityRaycastFloor9': 'BgCheck_EntityRaycastDown9',

  'WaterBox_GetCamDataIndex': 'WaterBox_GetBgCamIndex',
  'WaterBox_GetCameraSType': 'WaterBox_GetBgCamSetting',
  'WaterBox_GetLightSettingIndex': 'WaterBox_GetLightIndex',
  'Camera_InitPlayerSettings': 'Camera_InitDataUsingPlayer',
  'Camera_GetSkyboxOffset': 'Camera_GetQuakeOffset',
  'Camera_ChangeDataIdx': 'Camera_ChangeBgCamIndex',
  'Camera_AddQuake': 'Camera_RequestQuake',
  'Camera_SetParam': 'Camera_SetViewParam',
  'Quake_Add': 'Quake_Request',
  'Quake_SetQuakeValues': 'Quake_SetPerturbations',
  'Quake_SetCountdown': 'Quake_SetDuration',
  'Actor_MoveForward': 'Actor_MoveXZGravity',
  'ShrinkWindow_SetVal': 'Letterbox_SetSizeTarget',
  'Interface_ChangeAlpha': 'Interface_ChangeHudVisibilityMode',
  'Player_ItemToActionParam': 'Player_ItemToItemAction',
  'Player_GetSwordHeld': 'Player_GetMeleeWeaponHeld',
  'Player_ActionToSword': 'Player_ActionToMeleeWeapon',
  'SurfaceType_IsHookshotSurface': 'SurfaceType_CanHookshot',
  'CollisionCheck_SpawnShieldParticlesMetalSound': 'CollisionCheck_SpawnShieldParticlesMetalSfx',
  'HealthMeter_Init': 'Health_InitMeter',
  'HealthMeter_Update': 'Health_UpdateMeter',
  'HealthMeter_Draw': 'Health_DrawMeter',
  'HealthMeter_HandleCriticalAlarm': 'Health_UpdateBeatingHeart',
  'HealthMeter_IsCritical': 'Health_IsCritical',
  'Select_Init': 'MapSelect_Init',
  'Select_Destroy': 'MapSelect_Destroy',
  'FileChoose_Init': 'FileSelect_Init',
  'FileChoose_Destroy': 'FileSelect_Destroy',

  'func_800ECC04': 'AudioOcarina_Start',
  'func_800EE824': 'AudioOcarina_PlayLongScarecrowSong',
  'func_800F5E18': 'Audio_PlaySequenceWithSeqPlayerIO',
  'func_800F6268': 'Audio_UpdateMalonSinging',
  'func_800F6584': 'Audio_ToggleMalonSinging',
  'func_800F47BC': 'Audio_SetBgmVolumeOffDuringFanfare',
  'func_800F6AB0': 'Audio_StopBgmAndFanfare',
  'func_800F3F3C': 'Audio_PlayCutsceneEffectsSequence',
  'func_8010BD58': 'Message_StartOcarina',
  'func_8010BD88': 'Message_StartOcarinaSunsSongDisabled',
  'func_800AA000': 'Rumble_Request',
  'func_80087708': 'Magic_RequestChange',
  'func_800C0CB8': 'Play_CamIsNotFixed',
  'func_800994A0': 'Scene_SetTransitionForNextEntrance',
  'func_80041D4C': 'SurfaceType_GetFloorType',
  'func_8004356C': 'DynaPolyActor_IsPlayerOnTop',
  'func_8005AC48': 'Camera_OverwriteStateFlags',
  'func_8005ACFC': 'Camera_SetStateFlag',
  'func_8003EBF8': 'DynaPoly_DisableCollision',
  'func_8003EC50': 'DynaPoly_EnableCollision',
  'func_8003ECA8': 'DynaPoly_DisableCeilingCollision',
  'func_8005AD1C': 'Camera_UnsetStateFlag',
  'func_800876C8': 'Magic_Reset',
  'func_8002D53C': 'TitleCard_Clear',
  'func_8002F7DC': 'Player_PlaySfx',
  'func_8083264C': 'Player_RequestRumble',
  'func_8085002C': 'Player_UpdateBunnyEars',
  'func_80832210': 'Player_ZeroSpeedXZ',
  'func_8002F434': 'Actor_OfferGetItem',
  'func_8002D9A4': 'Actor_SetProjectileSpeed',
  'func_8002BE04': 'Actor_ProjectPos',
  'func_8002D7EC': 'Actor_UpdatePos',
  'func_8002D868': 'Actor_UpdateVelocityXZGravity',
  'func_8002D908': 'Actor_UpdateVelocityXYZ',
  'func_8002D97C': 'Actor_MoveXYZ',
  'func_8002F554': 'Actor_OfferGetItemNearby',
  'func_8002F580': 'Actor_OfferCarry',
  'func_8002F5F0': 'Actor_SetClosestSecretDistance',
  'func_800304DC': 'Actor_InitContext',
  'func_80031A28': 'Actor_KillAllWithMissingObject',
  'func_80033DB8': 'Actor_RequestQuake',
  'func_80033E1C': 'Actor_RequestQuakeWithSpeed',
  'func_80033E88': 'Actor_RequestQuakeAndRumble',
  'func_80038290': 'Actor_TrackPlayer',
  'func_80088AA0': 'Interface_SetSubTimer',
  'func_80088AF0': 'Interface_SetSubTimerToFinalSecond',
  'func_80088B34': 'Interface_SetTimer',
  'func_80110990': 'Interface_Destroy',
  'func_801109B0': 'Interface_Init',
};

const z64playerMap = {
  'ITEM00_HEART': 'ITEM00_RECOVERY_HEART',
  'PLAYER_SWORD_BGS': 'PLAYER_SWORD_BIGGORON',
  'PLAYER_ANIMGROUP_0': 'PLAYER_ANIMGROUP_wait',
  'PLAYER_ANIMGROUP_1': 'PLAYER_ANIMGROUP_walk',
  'PLAYER_ANIMGROUP_2': 'PLAYER_ANIMGROUP_run',
  'PLAYER_ANIMGROUP_3': 'PLAYER_ANIMGROUP_damage_run',
  'PLAYER_ANIMGROUP_4': 'PLAYER_ANIMGROUP_heavy_run',
  'PLAYER_ANIMGROUP_5': 'PLAYER_ANIMGROUP_waitL',
  'PLAYER_ANIMGROUP_6': 'PLAYER_ANIMGROUP_waitR',
  'PLAYER_ANIMGROUP_7': 'PLAYER_ANIMGROUP_wait2waitR',
  'PLAYER_ANIMGROUP_8': 'PLAYER_ANIMGROUP_normal2fighter',
  'PLAYER_ANIMGROUP_9': 'PLAYER_ANIMGROUP_doorA_free',
  'PLAYER_ANIMGROUP_10': 'PLAYER_ANIMGROUP_doorA',
  'PLAYER_ANIMGROUP_11': 'PLAYER_ANIMGROUP_doorB_free',
  'PLAYER_ANIMGROUP_12': 'PLAYER_ANIMGROUP_doorB',
  'PLAYER_ANIMGROUP_13': 'PLAYER_ANIMGROUP_carryB',
  'PLAYER_ANIMGROUP_14': 'PLAYER_ANIMGROUP_landing',
  'PLAYER_ANIMGROUP_15': 'PLAYER_ANIMGROUP_short_landing',
  'PLAYER_ANIMGROUP_16': 'PLAYER_ANIMGROUP_landing_roll',
  'PLAYER_ANIMGROUP_17': 'PLAYER_ANIMGROUP_hip_down',
  'PLAYER_ANIMGROUP_18': 'PLAYER_ANIMGROUP_walk_endL',
  'PLAYER_ANIMGROUP_19': 'PLAYER_ANIMGROUP_walk_endR',
  'PLAYER_ANIMGROUP_20': 'PLAYER_ANIMGROUP_defense',
  'PLAYER_ANIMGROUP_21': 'PLAYER_ANIMGROUP_defense_wait',
  'PLAYER_ANIMGROUP_22': 'PLAYER_ANIMGROUP_defense_end',
  'PLAYER_ANIMGROUP_23': 'PLAYER_ANIMGROUP_side_walk',
  'PLAYER_ANIMGROUP_24': 'PLAYER_ANIMGROUP_side_walkL',
  'PLAYER_ANIMGROUP_25': 'PLAYER_ANIMGROUP_side_walkR',
  'PLAYER_ANIMGROUP_26': 'PLAYER_ANIMGROUP_45_turn',
  'PLAYER_ANIMGROUP_27': 'PLAYER_ANIMGROUP_waitL2wait',
  'PLAYER_ANIMGROUP_28': 'PLAYER_ANIMGROUP_waitR2wait',
  'PLAYER_ANIMGROUP_29': 'PLAYER_ANIMGROUP_throw',
  'PLAYER_ANIMGROUP_30': 'PLAYER_ANIMGROUP_put',
  'PLAYER_ANIMGROUP_31': 'PLAYER_ANIMGROUP_back_walk',
  'PLAYER_ANIMGROUP_32': 'PLAYER_ANIMGROUP_check',
  'PLAYER_ANIMGROUP_33': 'PLAYER_ANIMGROUP_check_wait',
  'PLAYER_ANIMGROUP_34': 'PLAYER_ANIMGROUP_check_end',
  'PLAYER_ANIMGROUP_35': 'PLAYER_ANIMGROUP_pull_start',
  'PLAYER_ANIMGROUP_36': 'PLAYER_ANIMGROUP_pulling',
  'PLAYER_ANIMGROUP_37': 'PLAYER_ANIMGROUP_pull_end',
  'PLAYER_ANIMGROUP_38': 'PLAYER_ANIMGROUP_fall_up',
  'PLAYER_ANIMGROUP_39': 'PLAYER_ANIMGROUP_jump_climb_hold',
  'PLAYER_ANIMGROUP_40': 'PLAYER_ANIMGROUP_jump_climb_wait',
  'PLAYER_ANIMGROUP_41': 'PLAYER_ANIMGROUP_jump_climb_up',
  'PLAYER_ANIMGROUP_42': 'PLAYER_ANIMGROUP_down_slope_slip_end',
  'PLAYER_ANIMGROUP_43': 'PLAYER_ANIMGROUP_up_slope_slip_end',
  'PLAYER_ANIMGROUP_44': 'PLAYER_ANIMGROUP_nwait',
};

const z64itemMap = {
  // EquipmentType
  'EQUIP_SWORD': 'EQUIP_TYPE_SWORD',
  'EQUIP_SHIELD': 'EQUIP_TYPE_SHIELD',
  'EQUIP_TUNIC': 'EQUIP_TYPE_TUNIC',
  'EQUIP_BOOTS': 'EQUIP_TYPE_BOOTS',
  // UpgradeType
  'UPG_STICKS': 'UPG_DEKU_STICKS',
  'UPG_NUTS': 'UPG_DEKU_NUTS',
  // QuestItem
  'QUEST_GERUDO_CARD': 'QUEST_GERUDOS_CARD',
  'QUEST_HEART_PIECE': 'QUEST_HEART_PIECE_COUNT',
  // DungeonItem
  'DUNGEON_KEY_BOSS': 'DUNGEON_BOSS_KEY',
  // InventorySlot
  'SLOT_STICK': 'SLOT_DEKU_STICK',
  'SLOT_NUT': 'SLOT_DEKU_NUT',
  'SLOT_LENS': 'SLOT_LENS_OF_TRUTH',
  'SLOT_BEAN': 'SLOT_MAGIC_BEAN',
  // ItemID
  'ITEM_STICK': 'ITEM_DEKU_STICK',
  'ITEM_NUT': 'ITEM_DEKU_NUT',
  'ITEM_OCARINA_TIME': 'ITEM_OCARINA_OF_TIME',
  'ITEM_LENS': 'ITEM_LENS_OF_TRUTH',
  'ITEM_BEAN': 'ITEM_MAGIC_BEAN',
  'ITEM_BOTTLE': 'ITEM_BOTTLE_EMPTY',
  'ITEM_POTION_RED': 'ITEM_BOTTLE_POTION_RED',
  'ITEM_POTION_GREEN': 'ITEM_BOTTLE_POTION_GREEN',
  'ITEM_POTION_BLUE': 'ITEM_BOTTLE_POTION_BLUE',
  'ITEM_FAIRY': 'ITEM_BOTTLE_FAIRY',
  'ITEM_FISH': 'ITEM_BOTTLE_FISH',
  'ITEM_MILK_BOTTLE': 'ITEM_BOTTLE_MILK_FULL',
  'ITEM_LETTER_RUTO': 'ITEM_BOTTLE_RUTOS_LETTER',
  'ITEM_BLUE_FIRE': 'ITEM_BOTTLE_BLUE_FIRE',
  'ITEM_BUG': 'ITEM_BOTTLE_BUG',
  'ITEM_BIG_POE': 'ITEM_BOTTLE_BIG_POE',
  'ITEM_MILK_HALF': 'ITEM_BOTTLE_MILK_HALF',
  'ITEM_POE': 'ITEM_BOTTLE_POE',
  'ITEM_LETTER_ZELDA': 'ITEM_ZELDAS_LETTER',
  'ITEM_MASK_BUNNY': 'ITEM_MASK_BUNNY_HOOD',
  'ITEM_SAW': 'ITEM_POACHERS_SAW',
  'ITEM_SWORD_BROKEN': 'ITEM_BROKEN_GORONS_SWORD',
  'ITEM_FROG': 'ITEM_EYEBALL_FROG',
  'ITEM_EYEDROPS': 'ITEM_EYE_DROPS',
  'ITEM_BOW_ARROW_FIRE': 'ITEM_BOW_FIRE',
  'ITEM_BOW_ARROW_ICE': 'ITEM_BOW_ICE',
  'ITEM_BOW_ARROW_LIGHT': 'ITEM_BOW_LIGHT',
  'ITEM_SWORD_BGS': 'ITEM_SWORD_BIGGORON',
  'ITEM_BRACELET': 'ITEM_STRENGTH_GORONS_BRACELET',
  'ITEM_GAUNTLETS_SILVER': 'ITEM_STRENGTH_SILVER_GAUNTLETS',
  'ITEM_GAUNTLETS_GOLD': 'ITEM_STRENGTH_GOLD_GAUNTLETS',
  'ITEM_SWORD_KNIFE': 'ITEM_GIANTS_KNIFE',
  'ITEM_WALLET_ADULT': 'ITEM_ADULTS_WALLET',
  'ITEM_WALLET_GIANT': 'ITEM_GIANTS_WALLET',
  'ITEM_SEEDS': 'ITEM_DEKU_SEEDS',
  'ITEM_GERUDO_CARD': 'ITEM_GERUDOS_CARD',
  'ITEM_KEY_BOSS': 'ITEM_DUNGEON_BOSS_KEY',
  'ITEM_COMPASS': 'ITEM_DUNGEON_COMPASS',
  'ITEM_KEY_SMALL': 'ITEM_SMALL_KEY',
  'ITEM_MAGIC_SMALL': 'ITEM_MAGIC_JAR_SMALL',
  'ITEM_MAGIC_LARGE': 'ITEM_MAGIC_JAR_BIG',
  'ITEM_SINGLE_MAGIC': 'ITEM_INVALID_1',
  'ITEM_DOUBLE_MAGIC': 'ITEM_INVALID_2',
  'ITEM_DOUBLE_DEFENSE': 'ITEM_INVALID_3',
  'ITEM_HEART': 'ITEM_RECOVERY_HEART',
  'ITEM_STICKS_5': 'ITEM_DEKU_STICKS_5',
  'ITEM_STICKS_10': 'ITEM_DEKU_STICKS_10',
  'ITEM_NUTS_5': 'ITEM_DEKU_NUTS_5',
  'ITEM_NUTS_10': 'ITEM_DEKU_NUTS_10',
  'ITEM_ARROWS_SMALL': 'ITEM_ARROWS_5',
  'ITEM_ARROWS_MEDIUM': 'ITEM_ARROWS_10',
  'ITEM_ARROWS_LARGE': 'ITEM_ARROWS_30',
  'ITEM_SEEDS_30': 'ITEM_DEKU_SEEDS_30',
  'ITEM_STICK_UPGRADE_20': 'ITEM_DEKU_STICK_UPGRADE_20',
  'ITEM_STICK_UPGRADE_30': 'ITEM_DEKU_STICK_UPGRADE_30',
  'ITEM_NUT_UPGRADE_30': 'ITEM_DEKU_NUT_UPGRADE_30',
  'ITEM_NUT_UPGRADE_40': 'ITEM_DEKU_NUT_UPGRADE_40',
  // GetItemID
  'GI_NUTS_5': 'GI_DEKU_NUTS_5',
  'GI_STICKS_1': 'GI_DEKU_STICKS_1',
  'GI_LENS': 'GI_LENS_OF_TRUTH',
  'GI_LETTER_ZELDA': 'GI_ZELDAS_LETTER',
  'GI_OCARINA_OOT': 'GI_OCARINA_OF_TIME',
  'GI_BOTTLE': 'GI_BOTTLE_EMPTY',
  'GI_POTION_RED': 'GI_BOTTLE_POTION_RED',
  'GI_POTION_GREEN': 'GI_BOTTLE_POTION_GREEN',
  'GI_POTION_BLUE': 'GI_BOTTLE_POTION_BLUE',
  'GI_FAIRY': 'GI_BOTTLE_FAIRY',
  'GI_MILK_BOTTLE': 'GI_BOTTLE_MILK_FULL',
  'GI_LETTER_RUTO': 'GI_BOTTLE_RUTOS_LETTER',
  'GI_BEAN': 'GI_MAGIC_BEAN',
  'GI_MASK_BUNNY': 'GI_MASK_BUNNY_HOOD',
  'GI_SAW': 'GI_POACHERS_SAW',
  'GI_SWORD_BROKEN': 'GI_BROKEN_GORONS_SWORD',
  'GI_FROG': 'GI_EYEBALL_FROG',
  'GI_EYEDROPS': 'GI_EYE_DROPS',
  'GI_GAUNTLETS_SILVER': 'GI_SILVER_GAUNTLETS',
  'GI_GAUNTLETS_GOLD': 'GI_GOLD_GAUNTLETS',
  'GI_SCALE_GOLD': 'GI_SCALE_GOLDEN',
  'GI_GERUDO_CARD': 'GI_GERUDOS_CARD',
  'GI_SEEDS_5': 'GI_DEKU_SEEDS_5',
  'GI_KEY_BOSS': 'GI_BOSS_KEY',
  'GI_MAP': 'GI_DUNGEON_MAP',
  'GI_KEY_SMALL': 'GI_SMALL_KEY',
  'GI_MAGIC_SMALL': 'GI_MAGIC_JAR_SMALL',
  'GI_MAGIC_LARGE': 'GI_MAGIC_JAR_LARGE',
  'GI_HEART': 'GI_RECOVERY_HEART',
  'GI_ARROWS_SMALL': 'GI_ARROWS_5',
  'GI_ARROWS_MEDIUM': 'GI_ARROWS_10',
  'GI_ARROWS_LARGE': 'GI_ARROWS_30',
  'GI_BRACELET': 'GI_GORONS_BRACELET',
  'GI_SWORD_BGS': 'GI_SWORD_BIGGORON',
  'GI_STICKS_5': 'GI_DEKU_STICKS_5',
  'GI_STICKS_10': 'GI_DEKU_STICKS_10',
  'GI_NUTS_5_2': 'GI_DEKU_NUTS_5_2',
  'GI_NUTS_10': 'GI_DEKU_NUTS_10',
  'GI_SEEDS_30': 'GI_DEKU_SEEDS_30',
  'GI_FISH': 'GI_BOTTLE_FISH',
  'GI_BUGS': 'GI_BOTTLE_BUGS',
  'GI_BLUE_FIRE': 'GI_BOTTLE_BLUE_FIRE',
  'GI_POE': 'GI_BOTTLE_POE',
  'GI_BIG_POE': 'GI_BOTTLE_BIG_POE',
  'GI_STICK_UPGRADE_20': 'GI_DEKU_STICK_UPGRADE_20',
  'GI_STICK_UPGRADE_30': 'GI_DEKU_STICK_UPGRADE_30',
  'GI_NUT_UPGRADE_30': 'GI_DEKU_NUT_UPGRADE_30',
  'GI_NUT_UPGRADE_40': 'GI_DEKU_NUT_UPGRADE_40',
  // GetItemDrawID
  'GID_BOTTLE': 'GID_BOTTLE_EMPTY',
  'GID_KEY_SMALL': 'GID_SMALL_KEY',
  'GID_HEART': 'GID_RECOVERY_HEART',
  'GID_KEY_BOSS': 'GID_BOSS_KEY',
  'GID_NUTS': 'GID_DEKU_NUTS',
  'GID_STICK': 'GID_DEKU_STICK',
  'GID_MAGIC_SMALL': 'GID_MAGIC_JAR_SMALL',
  'GID_MAGIC_LARGE': 'GID_MAGIC_JAR_LARGE',
  'GID_GERUDO_CARD': 'GID_GERUDOS_CARD',
  'GID_ARROWS_SMALL': 'GID_ARROWS_5',
  'GID_ARROWS_MEDIUM': 'GID_ARROWS_10',
  'GID_ARROWS_LARGE': 'GID_ARROWS_30',
  'GID_OCARINA_TIME': 'GID_OCARINA_OF_TIME',
  'GID_MILK': 'GID_BOTTLE_MILK_FULL',
  'GID_LENS': 'GID_LENS_OF_TRUTH',
  'GID_POTION_GREEN': 'GID_BOTTLE_POTION_GREEN',
  'GID_POTION_RED': 'GID_BOTTLE_POTION_RED',
  'GID_POTION_BLUE': 'GID_BOTTLE_POTION_BLUE',
  'GID_LETTER_ZELDA': 'GID_ZELDAS_LETTER',
  'GID_BEAN': 'GID_MAGIC_BEAN',
  'GID_SAW': 'GID_POACHERS_SAW',
  'GID_SWORD_BGS': 'GID_SWORD_BIGGORON',
  'GID_CHICKEN': 'GID_CUCCO',
  'GID_LETTER_RUTO': 'GID_BOTTLE_RUTOS_LETTER',
  'GID_SEEDS': 'GID_DEKU_SEEDS',
  'GID_GAUNTLETS_SILVER': 'GID_SILVER_GAUNTLETS',
  'GID_GAUNTLETS_GOLD': 'GID_GOLD_GAUNTLETS',
  'GID_MASK_BUNNY': 'GID_MASK_BUNNY_HOOD',
  'GID_EYEDROPS': 'GID_EYE_DROPS',
  'GID_SWORD_BROKEN': 'GID_BROKEN_GORONS_SWORD',
  'GID_BRACELET': 'GID_GORONS_BRACELET',
  'GID_FROG': 'GID_EYEBALL_FROG',
  // ExchangeItemID
  'EXCH_ITEM_LETTER_ZELDA': 'EXCH_ITEM_ZELDAS_LETTER',
  'EXCH_ITEM_BEAN': 'EXCH_ITEM_MAGIC_BEAN',
  'EXCH_ITEM_SAW': 'EXCH_ITEM_POACHERS_SAW',
  'EXCH_ITEM_SWORD_BROKEN': 'EXCH_ITEM_BROKEN_GORONS_SWORD',
  'EXCH_ITEM_FROG': 'EXCH_ITEM_EYEBALL_FROG',
  'EXCH_ITEM_EYEDROPS': 'EXCH_ITEM_EYE_DROPS',
  'EXCH_ITEM_MASK_BUNNY': 'EXCH_ITEM_MASK_BUNNY_HOOD',
  'EXCH_ITEM_FISH': 'EXCH_ITEM_BOTTLE_FISH',
  'EXCH_ITEM_BLUE_FIRE': 'EXCH_ITEM_BOTTLE_BLUE_FIRE',
  'EXCH_ITEM_BUG': 'EXCH_ITEM_BOTTLE_BUG',
  'EXCH_ITEM_POE': 'EXCH_ITEM_BOTTLE_POE',
  'EXCH_ITEM_BIG_POE': 'EXCH_ITEM_BOTTLE_BIG_POE',
  'EXCH_ITEM_LETTER_RUTO': 'EXCH_ITEM_BOTTLE_RUTOS_LETTER',
  // sItemActionParams
  'PLAYER_IA_STICK': 'PLAYER_IA_DEKU_STICK',
  'PLAYER_IA_NUT': 'PLAYER_IA_DEKU_NUT',
  'PLAYER_IA_OCARINA_TIME': 'PLAYER_IA_OCARINA_OF_TIME',
  'PLAYER_IA_LENS': 'PLAYER_IA_LENS_OF_TRUTH',
  'PLAYER_IA_BEAN': 'PLAYER_IA_MAGIC_BEAN',
  'PLAYER_IA_BOTTLE_MILK': 'PLAYER_IA_BOTTLE_MILK_FULL',
  'PLAYER_IA_BOTTLE_LETTER': 'PLAYER_IA_BOTTLE_RUTOS_LETTER',
  'PLAYER_IA_LETTER_ZELDA': 'PLAYER_IA_ZELDAS_LETTER',
  'PLAYER_IA_MASK_BUNNY': 'PLAYER_IA_MASK_BUNNY_HOOD',
  'PLAYER_IA_SAW': 'PLAYER_IA_POACHERS_SAW',
  'PLAYER_IA_SWORD_BROKEN': 'PLAYER_IA_BROKEN_GORONS_SWORD',
  'PLAYER_IA_SWORD_BGS': 'PLAYER_IA_SWORD_BIGGORON',
}

const maps = [z64sceneMap, variablesMap, functionsMap, z64itemMap, z64playerMap];

// Regex patterns to match and replace
function processFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  let updatedContent = content;

  maps.forEach((map) => {
    Object.keys(map).forEach((before) => {
      const after = map[before];
      const beforeRegex = new RegExp(`\\b${before}\\b`, 'g');
      updatedContent = updatedContent.replace(beforeRegex, after);
    });
  });

  fs.writeFileSync(filePath, updatedContent, 'utf8');
}

// Recursive function to process files in a directory
function processFiles(dirPath) {
  const files = fs.readdirSync(dirPath);

  files.forEach((file) => {
    const filePath = path.join(dirPath, file);
    const stat = fs.statSync(filePath);

    if (stat.isDirectory() && !filePath.match(/\.git$/)) {
      processFiles(filePath);
    } else if (C_FILES_REGEX.test(file)) {
      processFile(filePath);
    }
  });
}

// Start processing files in the directory
processFiles(__dirname);
